name: rugby_stats
version: 1.0.0
profile: rugby_stats

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

models:
  rugby_stats:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
